services:
  gateway:
    build: ./api-gateway/api-gateway
    ports:
      - 8080:8080
    networks: ["appnet"]

  demo-service:
    build: ./DemoService
    ports:
      - 8082:8082
    networks: ["appnet"]

  auth-service:
    build: ./AuthService
    ports:
      - 8083:8083
    environment:
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: rs-exam-project
      KEYCLOAK_CLIENT_ID: exam-client
      KEYCLOAK_CLIENT_SECRET: EXaY421MSh4qC1z0pag1upXumwAvXh2t
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks: ["appnet"]


  # ---------- Databases ----------
  postgres-app:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
    networks:
      - backend

  postgres-keycloak:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kcuser
      POSTGRES_PASSWORD: kcpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_kc_data:/var/lib/postgresql/data
    networks:
      - backend

  # ---------- RabbitMQ ----------
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbitpass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

  # ---------- Redis ----------
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  # ---------- MinIO ----------
  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend

  # Optional: auto-create bucket (удобно для file-service)
  minio-init:
    image: minio/mc:RELEASE.2025-01-17T23-25-50Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 minio minio12345) do
        echo 'waiting for minio...' && sleep 2;
      done;
      /usr/bin/mc mb -p local/files || true;
      /usr/bin/mc anonymous set download local/files || true;
      echo 'MinIO bucket ready';
      "
    networks:
      - backend

  # ---------- Monitoring ----------
  prometheus:
    image: prom/prometheus:v3.0.1
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:11.4.0
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
  appnet:
    external: true


volumes:
  postgres_app_data:
  postgres_kc_data:
  rabbitmq_data:
  redis_data:
  minio_data:
  prometheus_data:
  grafana_data:
