global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8083"]

  - job_name: file-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["file-service:8084"]

  - job_name: processing-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["processing-service:8085"]

  - job_name: demo-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["demo-service:8082"]
