server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/rs-exam-project}
  cloud:
    gateway:
      routes:
        - id: demo
          uri: http://demo-service:8082
          predicates:
            - Path=/api/demo/**
          filters:
            - StripPrefix=2
        - id: auth
          uri: http://auth-service:8083
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: auth-short
          uri: http://auth-service:8083
          predicates:
            - Path=/login,/register
          filters:
            - RewritePath=/(?<segment>.*),/auth/${segment}